" author: Jinwoo Baek
" 
" ~/.vimrc 

set nocompatible              " be iMproved, required
filetype off                  " required
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'tpope/vim-fugitive'
Plugin 'hynek/vim-python-pep8-indent'
Plugin 'vim-ruby/vim-ruby'
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
Plugin 'L9'
Plugin 'easymotion/vim-easymotion'

"Plugin 'tpope/vim-surround'
"Plugin 'scrooloose/syntastic'
call vundle#end()

set nocompatible                  " Must come first because it changes other options.
"set autoindent
"set sts=2
"set smartindent
"set autoindent
"set expandtab                    " Use spaces instead of tabs

syntax on             " Enable syntax highlighting
filetype on           " Enable filetype detection
filetype indent on    " Enable filetype-specific indenting
filetype plugin on    " Enable filetype-specific plugins
set tabstop=2
set shiftwidth=2
set expandtab

set showmode                      " Display the mode you're in.

set hidden                        " Handle multiple buffers better.

"set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell.

set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.

set number                        " Show line numbers.
set ruler                         " Show cursor position.

set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.

set wrap                          " Turn on line wrapping.
set scrolloff=3                   " Show 3 lines of context around the cursor.

set title                         " Set the terminal's title

set visualbell                    " No beeping.

set swapfile
set dir=~/.vim/tmp
set backspace=indent,eol,start
let mapleader=","

"" Useful status information at bottom of screen
"set statusline=[%n]\ %<%.99f\ %h%w%m%r%y\ %{fugitive#statusline()}%{exists('*CapsLockStatusline')?CapsLockStatusline():''}%=%-16(\ %l,%c-%v\ %)%P
"
" Tab mappings.
map <leader>tt :tabnew<cr>
map <leader>te :tabedit
map <leader>tc :tabclose<cr>
map <leader>to :tabonly<cr>
map <leader>tn :tabnext<cr>
map <leader>tp :tabprevious<cr>
map <leader>tf :tabfirst<cr>
map <leader>tl :tablast<cr>
map <leader>tm :tabmove

" FuzzyFinder
nnoremap <silent> <C-f>p     :FufFile<CR>
nnoremap <silent> <C-f>b     :FufBuffer<CR>
nnoremap <silent> <C-f>f     :FufCoverageFile<CR>
nnoremap <silent> <C-f>r     :FufRenewCache<CR>


map <C-n> :NERDTreeToggle<CR>
map <Leader>f :w<CR>:!./runner.sh<CR>

autocmd FileType ruby compiler ruby
