#!/usr/bin/env ruby

require_relative 'vim_setup'
require_relative 'wget_setup'
require_relative 'homebrew_setup'
require_relative 'alfred_setup'
require_relative 'bashrc_setup'
require_relative 'xcode_setup'
require_relative 'git_setup'
require_relative 'iterm_setup'
require_relative 'karabiner_setup'
require_relative 'seil_setup'
require_relative 'setup_reminder'
require_relative 'run_apple_scripts'
require_relative 'setup_dropbox'
